
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webchat-deployment
  labels:
    app: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat
  template:
    metadata:
      labels:
        app: webchat
    spec:
      containers:
      - name: weberver
        image: hagbesit/webchat:latest
        ports:
        - containerPort: 3030
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: webchat-service
spec:
  selector:
    app: webchat
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3030
    nodePort: 31110
